SELECT COUNT(*)
    FROM A_PREVE1
    JOIN A_CLIENT  ON A_PREVE1.C_CLIENTE   = A_CLIENT.C_CODIGO
    JOIN A_PREVE2  ON A_PREVE1.C_NUMERO    = A_PREVE2.C_NUMERO
    JOIN A_MOVIME  ON A_PREVE1.C_NUMERO    = A_MOVIME.C_PEDIDO
    JOIN A_PRODUT  ON A_PRODUT.C_CODIGO    = A_PREVE2.C_CODPROD
    JOIN A_PRECOS  ON A_PRECOS.C_CODPROD   = A_PRODUT.C_CODIGO
    JOIN A_CONTAS  ON A_MOVIME.C_CODVEND   = A_CONTAS.C_RFVENDED
                AND A_CONTAS.C_CODCF     = A_CLIENT.C_CODIGO
    JOIN A_HPCONT  ON A_CONTAS.C_CHAVE     = A_HPCONT.C_CHAVE
    WHERE A_HPCONT.C_DATA BETWEEN :start_date AND :end_date

