SELECT
    A_MOVIME.C_CODVEND,
    A_CLIENT.C_CODIGO,
    A_CLIENT.C_CLIENTE,
    A_PREVE1.C_NUMERO,
    A_PREVE1.C_DATA AS DATA_PEDIDO,
    A_MOVIME.C_NTFISCAL,
    A_MOVIME.C_DATA AS DATA_MOVIMENTO,
    A_PRODUT.C_CODIGO AS COD_PRODUTO,
    A_PRODUT.C_DESCR AS DESC_PRODUTO,
    A_PRECOS.C_PRCUSTO,
    ROUND(A_PREVE2.C_PRECO, 2) AS C_PRECO,
    ROUND(A_PREVE2.C_PRECO - A_PRECOS.C_PRCUSTO, 2) AS MARGEM_VALOR,
    CASE 
        WHEN A_PRECOS.C_PRCUSTO = 0 THEN NULL
        ELSE ROUND(((A_PREVE2.C_PRECO - A_PRECOS.C_PRCUSTO) / A_PRECOS.C_PRCUSTO) * 100, 2)
    END AS MARGEM_PORCENTAGEM,
    A_HPCONT.C_VALOR,
    A_HPCONT.C_DATA AS DATA_PAGAMENTO,
    ROUND(SUM(A_PREVE2.C_PRECO) OVER (PARTITION BY A_MOVIME.C_NTFISCAL), 2) AS TOTAL_NOTA,
    ROUND(
        AVG(
        CASE 
            WHEN A_PRECOS.C_PRCUSTO = 0 THEN NULL
            ELSE ((A_PREVE2.C_PRECO - A_PRECOS.C_PRCUSTO) / A_PRECOS.C_PRCUSTO) * 100
        END
        ) OVER (PARTITION BY A_MOVIME.C_CODVEND), 2
    ) AS MEDIA_MARGEM_PORCENT_VENDEDOR,
    ROUND(A_HPCONT.C_VALOR * 0.025, 2) AS VALOR_2_5_PORCENTO
    FROM A_PREVE1
    JOIN A_CLIENT  ON A_PREVE1.C_CLIENTE   = A_CLIENT.C_CODIGO
    JOIN A_PREVE2  ON A_PREVE1.C_NUMERO    = A_PREVE2.C_NUMERO
    JOIN A_MOVIME  ON A_PREVE1.C_NUMERO    = A_MOVIME.C_PEDIDO
    JOIN A_PRODUT  ON A_PRODUT.C_CODIGO    = A_PREVE2.C_CODPROD
    JOIN A_PRECOS  ON A_PRECOS.C_CODPROD   = A_PRODUT.C_CODIGO
    JOIN A_CONTAS  ON A_MOVIME.C_CODVEND   = A_CONTAS.C_RFVENDED
                AND A_CONTAS.C_CODCF     = A_CLIENT.C_CODIGO
    JOIN A_HPCONT  ON A_CONTAS.C_CHAVE     = A_HPCONT.C_CHAVE
    WHERE A_HPCONT.C_DATA BETWEEN :start_date AND :end_date
    ORDER BY A_MOVIME.C_NTFISCAL, A_PREVE1.C_NUMERO, A_PRODUT.C_CODIGO
    LIMIT :limit
    OFFSET :offset